dist: bionic

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 8.1.0

env:
  - XDEBUG_MODE=coverage

before_script:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
